### ISSUE TITLE
can not start the dqn_pixel_atari agent

### ISSUE THREAD

**Issue by SinaDitzel** [ShangtongZhang/DeepRL#15]
if I start the dqn_pixel_atari('PongNoFrameskip-v4') or the dqn_pixel_atari('BreakoutNoFrameskip-v4') agent, I receive an error message:

```
Traceback (most recent call last):
  File "main.py", line 283, in <module>
    dqn_pixel_atari('PongNoFrameskip-v4')
  File "main.py", line 84, in dqn_pixel_atari
    run_episodes(DQNAgent(config))
  File ".../DeepRL/DeepRL/utils/misc.py", line 21, in run_episodes
    reward, step = agent.episode()
  File ".../DeepRL/DeepRL/agent/DQN_agent.py", line 54, in episode
    self.replay.feed([state, action, reward, next_state, int(done)])
  File ".../DeepRL/DeepRL/component/replay.py", line 32, in feed
    self.states = np.empty((self.memory_size, ) + state.shape, dtype=self.dtype)
MemoryError
```

Any idea what is the error? Thanks !

**Comment by ShangtongZhang** [comment]
Your machine doesn't have enough memory. You may need to reduce the replay buffer size.
