### ISSUE TITLE
No Monitor Files

### ISSUE THREAD

**Issue by shisi-cc** [ShangtongZhang/DeepRL#40]
When I run the code examples.py an error is raised
```
Traceback (most recent call last):
  File "examples.py", line 445, in <module>
    plot()
  File "examples.py", line 391, in plot
    data = plotter.load_results(names)
  File "plot.py", line 47, in load_results
    ts = load_monitor_log(dir)
  File "bench.py", line 107, in load_monitor_log
    raise LoadMonitorResultsError("no monitor files of the form *%s found in %s" % (Monitor.EXT, dir))
deep_rl.component.bench.LoadMonitorResultsError: no monitor files of the form *monitor.csv found in ./log
```
I wonder whether there is something wrong with the generation of monitor file

**Comment by ShangtongZhang** [comment]
you cannot plot until you have something to plot. by default for toy tasks there is no log file.
