### ISSUE TITLE
Running examples.py

### ISSUE THREAD

**Issue by yngtodd** [ShangtongZhang/DeepRL#45]
Hey ShangtonZhang,

Thanks for putting this library up! I am having a bit of trouble running `examples.py` with cuda (cpu version is working fine):
```
(python35) [ygx@benson DeepRL]$ python examples.py 
Traceback (most recent call last):
  File "examples.py", line 560, in <module>
    dqn_pixel_atari(game)
  File "examples.py", line 66, in dqn_pixel_atari
    run_steps(DQNAgent(config))
  File "/home/ygx/libraries/DeepRL/deep_rl/agent/DQN_agent.py", line 54, in __init__
    self.actor.set_network(self.network)
  File "/home/ygx/libraries/DeepRL/deep_rl/agent/BaseAgent.py", line 129, in set_network
    self.__pipe.send([self.NETWORK, net])
  File "/home/ygx/libraries/anaconda3/envs/python35/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/home/ygx/libraries/anaconda3/envs/python35/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/ygx/libraries/anaconda3/envs/python35/lib/python3.5/site-packages/torch/multiprocessing/reductions.py", line 179, in reduce_storage
    raise RuntimeError("Cannot pickle CUDA storage; try pickling a CUDA tensor instead")
RuntimeError: Cannot pickle CUDA storage; try pickling a CUDA tensor instead
```
I was running the DQN on breakout. Here are the lines I uncommented in `examples.py`:
```
if __name__ == '__main__':                                                      
    mkdir('data/video')                                                         
    mkdir('dataset')                                                            
    mkdir('log')                                                                
    set_one_thread()                                                            
    select_device(1)                                                            
    # select_device(0)                                                                                                    
                                    
    game = 'Breakout'                                                           
    dqn_pixel_atari(game)                                                       
    # quantile_regression_dqn_pixel_atari(game)                                 
    #categorical_dqn_pixel_atari(game)                                          
    # a2c_pixel_atari(game)                                                     
    # n_step_dqn_pixel_atari(game)                                              
    #option_ciritc_pixel_atari(game)                                            
    # ppo_pixel_atari(game)                                                     
    # dqn_ram_atari(game)                                                       
    #ddpg_pixel()                                                               
                                                                                 
    # action_conditional_video_prediction()                                                                                                                      
    # plot()
```
I am using on a Linux machine with a couple V100s, using Python 3.5 and Pytorch 0.4.1.post2. I also tried Python 3.6 and Pytorch 1.0rc1.

**Comment by ShangtongZhang** [comment]
I have no idea what's going on. I run it last week in my server it worked well. I would suggest you set up nvidia-docker and build a docker container according to the docker file.

**Comment by yngtodd** [comment]
Thanks! I will do a bit more digging but will close this for now.

**Comment by ghost** [comment]
Hi ShangtonZhang,

  I am running your examples.py with the following lines in the main:
   if __name__ == '__main__':
    mkdir('log')
    mkdir('tf_log')
    set_one_thread()
    random_seed()
    select_device(-1)
    #select_device(0)

    # dqn_cart_pole()
    quantile_regression_dqn_cart_pole()
    # categorical_dqn_cart_pole()

However, I got this error:
Traceback (most recent call last):
  File "examples.py", line 445, in <module>
    quantile_regression_dqn_cart_pole()
  File "examples.py", line 89, in quantile_regression_dqn_cart_pole
    run_steps(QuantileRegressionDQNAgent(config))
  File "C:\ShangtongZhang\code\deep_rl\agent\QuantileRegressionDQN_agent.py", line 38, in __init__
    self.actor = QuantileRegressionDQNActor(config)
  File "C:\ShangtongZhang\code\deep_rl\agent\QuantileRegressionDQN_agent.py", line 16, in __init__
    self.start()
  File "C:\Users\w\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\w\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\w\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\w\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\w\AppData\Local\Programs\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ArgumentParser.__init__.<locals>.identity'

     Thanks for your help!
     I can run your: a2c_cart_pole()

     W

**Comment by zepinglee** [comment]
I got the same `RuntimeError: Cannot pickle CUDA storage` on pytorch 0.4.1 and it was gone after I downgraded pytorch to 0.4.0 .

As soumith replied, it is a bug in 0.4.1 (https://github.com/pytorch/pytorch/issues/9996#issuecomment-429072897)

**Comment by ghost** [comment]
Thanks zepinglee  for your comments! I tried 0.4.0  as well as 4.5.4, but they all did not work. I am using Windows 10, but these programs are created in a Mac.

**Comment by ShangtongZhang** [comment]
I highly recommend to use the Dockerfile.

**Comment by awarebayes** [comment]
Same thing. Everyones suggesting installing torch 0.4 instead
