### ISSUE TITLE
quantile_regression_dqn_cart_pole()

### ISSUE THREAD

**Issue by ghost** [ShangtongZhang/DeepRL#47]
Hi ShangtonZhang,

I am running your examples.py with the following lines in the main:

if name == 'main':
mkdir('log')
mkdir('tf_log')
set_one_thread()
random_seed()
select_device(-1)
#select_device(0)
quantile_regression_dqn_cart_pole()

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
However, I got this error:
Traceback (most recent call last):
File "examples.py", line 445, in 
quantile_regression_dqn_cart_pole()
File "examples.py", line 89, in quantile_regression_dqn_cart_pole
run_steps(QuantileRegressionDQNAgent(config))
File "C:\ShangtongZhang\code\deep_rl\agent\QuantileRegressionDQN_agent.py", line 38, in init
self.actor = QuantileRegressionDQNActor(config)
File "C:\ShangtongZhang\code\deep_rl\agent\QuantileRegressionDQN_agent.py", line 16, in init
self.start()
File "C:\Users\w\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
self._popen = self._Popen(self)
File "C:\Users\w\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "C:\Users\w\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
return Popen(process_obj)
File "C:\Users\w\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in init
reduction.dump(process_obj, to_child)
File "C:\Users\w\AppData\Local\Programs\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ArgumentParser.init..identity'

 Thanks for your help!
 I can run your: a2c_cart_pole()

 W

**Comment by ShangtongZhang** [comment]
I just tested it. It works well in my MacOS.  You can close async replay (https://github.com/ShangtongZhang/DeepRL/blob/master/examples.py#L21)  and async actor (https://github.com/ShangtongZhang/DeepRL/blob/master/examples.py#L33) as in ```dqn_cart_pole```. Then it should work. If it still doesn't work, please use the Dockerfile in the repo.
