### ISSUE TITLE
Rendering with DummyVecEnv

### ISSUE THREAD

**Issue by Marianoetchart** [ShangtongZhang/DeepRL#55]
Hi I would like to render with DummyVecEnv but I get an error back saying it has not been implemented from baselines/common/vec_env/vec_env.py. How would I go about to implement rendering. Here is the traceback, any help would be appreciated: 

```
Traceback (most recent call last):
  File "examples.py", line 473, in <module>
    dqn_pixel_atari(game)
  File "examples.py", line 80, in dqn_pixel_atari
    evaluate_game.evaluate_game(DRQNAgent(config),log, name)
  File "/home/mariano/Documents/DeepRL-0.3/evaluate_game.py", line 18, in evaluate_game
    task.render()
  File "/home/mariano/Documents/DeepRL-0.3/deep_rl/component/envs.py", line 203, in render
    return self.env.render()
  File "/home/mariano/Documents/DeepRL-0.3/baselines/baselines/common/vec_env/vec_env.py", line 111, in render
    imgs = self.get_images()
  File "/home/mariano/Documents/DeepRL-0.3/baselines/baselines/common/vec_env/vec_env.py", line 125, in get_images
    raise NotImplementedError
NotImplementedError
```

**Comment by ShangtongZhang** [comment]
Unfortunately I don't know. I assume it will be easy, you can just delegate the rendering from subprocess to the main process.

**Comment by Marianoetchart** [comment]
Figured it out, thanks for the quick reply!
