### ISSUE TITLE
size mismatch error for Gym Toy text environments

### ISSUE THREAD

**Issue by RaviTej310** [ShangtongZhang/DeepRL#65]
Hi. I've been able to run the code without any problems on the Classic Control environments like CartPole-v1. However, I get a size mismatch error when I try to run the algorithms on the toy text gym environments like Taxi-v2 and FrozenLake-v0. I get the same error when trying to run option_critic_feature, pp_feature or dqn_feature, so the problem is not related to the learning algorithm I suppose. 

Error:

`root - INFO: steps 0, 349525333.33 steps/s`<br/>`
Traceback (most recent call last):`<br/>`
  File "examples.py", line 500, in <module>`<br/>`
    option_critic_feature(game=game)`<br/>`
  File "examples.py", line 315, in option_critic_feature`<br/>`
    run_steps(OptionCriticAgent(config))`<br/>`
  File "/Users/ravi/Desktop/msc_code/dfdo/Dfdo/deep_rl/utils/misc.py", line 32, in run_steps
    agent.step()`<br/>`
  File "/Users/ravi/Desktop/msc_code/dfdo/Dfdo/deep_rl/agent/OptionCritic_agent.py", line 56, in step`<br/>`
    prediction = self.network(self.states)`<br/>`
  File "/Users/ravi/miniconda3/envs/dfdo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__`<br/>`
    result = self.forward(*input, **kwargs)`<br/>`
  File "/Users/ravi/Desktop/msc_code/dfdo/Dfdo/deep_rl/network/network_heads.py", line 85, in forward`<br/>`
    phi = self.body(tensor(x))`<br/>`
  File "/Users/ravi/miniconda3/envs/dfdo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__`<br/>`
    result = self.forward(*input, **kwargs)`<br/>`
  File "/Users/ravi/Desktop/msc_code/dfdo/Dfdo/deep_rl/network/network_bodies.py", line 53, in forward`<br/>`
    x = self.gate(layer(x))`<br/>`
  File "/Users/ravi/miniconda3/envs/dfdo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__`<br/>`
    result = self.forward(*input, **kwargs)`<br/>`
  File "/Users/ravi/miniconda3/envs/dfdo/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward`<br/>`
    return F.linear(input, self.weight, self.bias)`<br/>`
  File "/Users/ravi/miniconda3/envs/dfdo/lib/python3.6/site-packages/torch/nn/functional.py", line 1371, in linear`<br/>`
    output = input.matmul(weight.t())`<br/>`
RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 64] at /Users/distiller/project/conda/conda-bld/pytorch_1565272679438/work/aten/src/TH/generic/THTensorMath.cpp:752`

**Comment by ShangtongZhang** [comment]
I never tried that domain. Maybe I can fix them when I use them in the future.
