### ISSUE TITLE
Issue of running async_cart_pole()

### ISSUE THREAD

**Issue by xuxie1031** [ShangtongZhang/DeepRL#8]
When I try to run async_cart_pole() in main.py, I received the following error:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xuxie/pytorch/Py3Virtual/DeepRL/agent/async_agent.py", line 23, in train
    worker = config.worker(config, learning_network, extra)
  File "/home/xuxie/pytorch/Py3Virtual/DeepRL/async_worker/one_step_q.py", line 16, in __init__
    self.worker_network = config.network_fn()
  File "main.py", line 30, in <lambda>
    config.network_fn = lambda: FCNet([4, 50, 200, 2])
  File "/home/xuxie/pytorch/Py3Virtual/DeepRL/network/shallow_network.py", line 17, in __init__
    BasicNet.__init__(self, optimizer_fn, gpu)
  File "/home/xuxie/pytorch/Py3Virtual/DeepRL/network/base_network.py", line 21, in __init__
    self.cuda()
  File "/home/xuxie/pytorch/Py3Virtual/lib/python3.6/site-packages/torch/nn/modules/module.py", line 147, in cuda
    return self._apply(lambda t: t.cuda(device_id))
  File "/home/xuxie/pytorch/Py3Virtual/lib/python3.6/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/home/xuxie/pytorch/Py3Virtual/lib/python3.6/site-packages/torch/nn/modules/module.py", line 124, in _apply
    param.data = fn(param.data)
  File "/home/xuxie/pytorch/Py3Virtual/lib/python3.6/site-packages/torch/nn/modules/module.py", line 147, in <lambda>
    return self._apply(lambda t: t.cuda(device_id))
  File "/home/xuxie/pytorch/Py3Virtual/lib/python3.6/site-packages/torch/_utils.py", line 66, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/home/xuxie/pytorch/Py3Virtual/lib/python3.6/site-packages/torch/cuda/__init__.py", line 266, in _lazy_new
    _lazy_init()
  File "/home/xuxie/pytorch/Py3Virtual/lib/python3.6/site-packages/torch/cuda/__init__.py", line 83, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
**RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method**

I also tried to add following lines in agent/async_agent.py:
# try:
#     mp.set_start_method('spawn')
# except RuntimeError:
#     pass

However, I received the following error:
AttributeError: Can't pickle local object 'async_cart_pole.<locals>.<lambda>'
But both Train() and Evaluate() methods are on the top of that module, shouldn't be unpickable.

BTW, I use the following command to run the script(inside python virtual environment):
python3.6 main.py

Do you know how to solve the above issue? Or is there any proper way to run the async methods?

Thx!

**Comment by ShangtongZhang** [comment]
Hi,
I just tested it. With OSX, python 2.7 and pytorch v0.2, it works well.
I think you can try `config.network_fn = lambda: FCNet([4, 50, 200, 2], gpu=False)` if you have cuda, as async methods cannot use GPU.
Hope it can help.

**Comment by xuxie1031** [comment]
Hi,
After making the same change with yours, the async methods are working now. Thanks again for your important hints!
